### ISSUE TITLE
A world Map

### ISSUE THREAD

**Issue by RacerXx** [r-o-b-o-t-o/azerothcore-armory#25]
### Describe your feature request or suggestion in detail

Can you make a world map to go with the armory? like chromiecraft has an example https://www.chromiecraft.com/en/playermap/

**Comment by r-o-b-o-t-o** [comment]
I'm not sure that a live map fits well into the scope of this project.
Also it would be reinventing the wheel, the source for the map you linked is available here: https://github.com/azerothcore/playermap

**Comment by RacerXx** [comment]
yeah i just found it and came here to delete this but you beat me to it :P
