### ISSUE TITLE
Armory names are not accent sensitive

### ISSUE THREAD

**Issue by Fluctisonant** [r-o-b-o-t-o/azerothcore-armory#29]
### Describe your feature request or suggestion in detail

Currently, the Armory is not accent sensitive. An example of displaying this would be looking up my Rogue, "Luna" on the Armory. If you are to click on my Rogue named "Luna", it will instead redirect to the Armory page of a character named "Lüna".

### Describe a possible solution to your suggestion

The problem stems from a collation issue. This could be fixed in two possible ways:

1. Example: SQL_Latin1_General_CP1_CI_AS (where AS would ensure that the collation is accent sensitive).

2. Instead of the name of the character being used on the URL, (e.g. https://www.chromiecraft.com/en/armory/?character/ChromieCraft/Luna), perhaps using IDs would ensure that this issue never occurs as every character should have a unique ID.

**Comment by r-o-b-o-t-o** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/16344
