### ISSUE TITLE
Is it possible to get descriptions of objects in another language?

### ISSUE THREAD

**Issue by MRafStudio** [r-o-b-o-t-o/azerothcore-armory#31]
### Your question

In the question, I’m starting from how much it is possible, instead of English, to get a description of character objects in any other language..

**Comment by r-o-b-o-t-o** [comment]
Append `?locale=xx` to every `power.js` import.
For instance:
```diff
                $("<script>")
-                       .attr("src", "{{aowow}}/static/widgets/power.js")
+                       .attr("src", "{{aowow}}/static/widgets/power.js?locale=ru")
                        .appendTo("body");
```

There are 3 imports you'd need to replace as of now:
https://github.com/search?q=repo%3Ar-o-b-o-t-o%2Fazerothcore-armory%20power.js&type=code
