### ISSUE TITLE
Icons are leading to deadlinks

### ISSUE THREAD

**Issue by NicholoDesanti** [r-o-b-o-t-o/azerothcore-armory#33]
### Current Behaviour

Currently the link structure for the links are   example: https://wotlkdb.com/static/images/wow/icons/medium/class_priest.jpg, but the https://wotkdb.com has updated their link structure.

### Expected behaviour

Images should load

### Reproduction steps

Follow install instructions and then launch server

### Server operating system

Windows 10, Linux, MacOS

### Client operating system and browser

All browsers

### Armory revision

v1.0.0

### AzerothCore revision (commit hash)

AzerothCore rev. e863873d4c80

**Comment by r-o-b-o-t-o** [comment]
I recommend using `https://wowgaming.altervista.org/aowow` instead, see https://github.com/r-o-b-o-t-o/azerothcore-armory/commit/13ae2e9b2db78550978f0f85b64175f9513aa866
