### ISSUE TITLE
Unable to Start

### ISSUE THREAD

**Issue by Sikksens** [r-o-b-o-t-o/azerothcore-armory#34]
### Your question

Hi there,

When trying to launch after building, I get this error:
`Error: ENOENT: no such file or directory, open '/var/www/html/armory/data/meta/charactercustomization2/1_0.json'`

I have all the requirements, unsure what the issue is.

**Comment by Sikksens** [comment]
ah ok was gonna try the direct .zip download as well but thought I'd check here first, so it must be that. thanks will give it a go now.

**Comment by r-o-b-o-t-o** [comment]
Thanks for reporting back, will remove the `fetchdata` method from the readme to avoid further issues
